### ISSUE TITLE
Update this portfolio website

### ISSUE THREAD

**Issue by rdx-rocket** [rdx-rocket/Portfolio_website#3]

**Comment by rdx-rocket** [comment]
To Update this portfolio use this branch:
`portfolio-Update`
via this command:
`git checkout portfolio-Update`

**Comment by anshulkumarx7** [comment]
what changes you want to have in this portfolio website?

**Comment by rdx-rocket** [comment]
@anshulkumarx7 I want Fully Optimize Portfolio if you have any you can make PR in this repository but inside a folder

**Comment by rdx-rocket** [comment]
@gauravmandall I merged your pr

**Comment by gauravmandall** [comment]
@rdx-rocket thanks for merging!

**Comment by rdx-rocket** [comment]
@anshulkumarx7 I'm closing this issue if you want to make pr then you can and I'll merge your pull request
